name: flame
channels:
  - rdkit
  - defaults
dependencies:
  - cherrypy=14.0.1
  - ipykernel=4.8.0
  - ipython=6.2.1
  - jinja2=2.10
  - matplotlib=2.1.2
  - notebook=5.4.0
  - numpy=1.14.0
  - pandas=0.22.0
  - pip=9.0.1
  - python=3.6.4
  - scipy=1.0.0
  - seaborn=0.8.1
  - setuptools=38.4.0
  - scikit-learn=0.19.1
  - statsmodels=0.8.0
  - rdkit=2017.09.3.0
  - pyyaml
  - pip:
     - "https://github.com/flatkinson/standardiser/archive/master.zip"

