# system settings
verbose_error: true
numCPUs: 1
mol_batch: series                    # series | objects | auto (not implemented!)

# input settings
input_type: molecule                  # molecule | data | ext_data
normalize_method:                     # null | standardize       
- standardize

ionize_method: null                   # null | moka
convert3D_method: null                # null | ETKDG
computeMD_method:                     # RDKit_properties | RDKit_md | padel | custom
- RDKit_properties

ext_input: false                      # external input source TRUE
model_set:                            # list of models used for producing input
- endpoint: MAGENTA                   # - model name
  version: 1                          # - model version
- endpoint: MAGENTA
  version: 2

# Output 
output_format:                        # JSON | TSV  (dump results to output.tsv and errors to error.tsv)
- JSON      
         
output_md: true                      # if true dump the MD generated to 'output_md.tsv'

# SDFile settings
SDFile_activity: activity             # str
SDFile_experimental: IC50             # str
SDFile_name:                          # str
- GENERIC_NAME                        
- name

# TSV settings
TSV_activity: activity                # str
TSV_objnames: true                    # true if the object names are in the first column
TSV_varnames: true                    # true if the variable names are in the first row

# modeling settings
modelingToolkit: internal             # internal | R | KNIME | custom
model: RF                             # RF | SVM | GNB | PLSR | PLSDA
modelAutoscaling: false               # true | false
quantitative: true
tune: false
imbalance: null                       # simple_subsampling
feature_selection: null               # Kbest | null
feature_number: auto                  # auto: Sets max features to 10% of entries | Number


ModelValidationCV: loo
ModelValidationLC: false
ModelValidationN: 2
ModelValidationP: 1

# SVM settings
SVM_parameters:
  C: 1.0
  class_weight: balanced
  coef0: 0.0
  decision_function_shape: ovr
  degree: 3
  epsilon: 0.1
  gamma: auto
  kernel: rbf
  probability: false
  random_state: 46
  shrinking: true
  tol: 0.001

SVM_optimize:
  C:
  - 1
  - 10
  - 100
  class_weight:
  - null
  - balanced
  coef0:
  - 0.0
  - 0.8
  - 100.0
  degree:
  - 1
  - 3
  - 5
  gamma:
  - auto
  kernel:
  - rbf
  random_state:
  - 46

# RF settings
RF_parameters:
  class_weight: balanced
  max_depth: null
  max_features: sqrt
  n_estimators: 200
  n_jobs: 1
  oob_score: true
  random_state: 46

RF_optimize:
  class_weight:
  - null
  - balanced
  max_features:
  - sqrt
  - log2
  n_estimators: !!python/object/apply:builtins.range
  - 25
  - 50
  - 75
  oob_score:
  - true
  random_state:
  - 46

#GNB settings
GNB_parameters:
  priors: null

#PLSR settings
PLSR_parameters:
  scale: false
  tol: 0.000006
  n_components: 3
  # Manual optimization returns the MCC for the diffent
  # number of latent variables considered in 
  # n_components (below) with the best threshold for
  # optimum MCC. auto uses sk-learn gridsearch
  # with the same paramters.
  optimize: manual   # manual | auto  

PLSR_optimize:
  n_components:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7

#PLSDA settings
PLSDA_parameters:
  scale: false
  tol: 0.000006
  n_components: 2
  threshold: null
  # Manual optimization returns the MCC for the diffent
  # number of latent variables considered in 
  # n_components (below) with the best threshold for
  # optimum MCC. auto uses sk-learn gridsearch
  # with the same paramters.
  optimize: manual   # manual | auto  

PLSDA_optimize:
  n_components:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  threshold:
  - 0.6
  - 0.4
  - 0.5

# conformal predictor settings
conformal: true
conformalSignificance: 0.2
