# system settings
verbose_error: true
numCPUs: 2

# input settings
input_type: molecule                  # molecule | data
normalize_method: standardize         # null | standardize
ionize_method: null                   # null | moka
convert3D_method: null                # null | ETKDG
computeMD_method:                     # RDKit_properties | RDKit_md | custom
- RDKit_md

# SDFile settings
SDFile_activity: activity             # str s
SDFile_experimental: IC50             # str
SDFile_name: GENERIC_NAME             # str

# modeling settings
modelingToolkit: internal             # internal | R | KNIME
model: RF                             # RF | SVM
modelAutoscaling: false               # true | false
quantitative: false
tune: false

ModelValidationCV: loo
ModelValidationLC: false
ModelValidationN: 2
ModelValidationP: 1

# SVM settings
SVM_parameters:
  C: 1.0
  class_weight: balanced
  coef0: 0.0
  decision_function_shape: ovr
  degree: 3
  epsilon: 0.1
  gamma: auto
  kernel: rbf
  probability: false
  random_state: 46
  shrinking: true
  tol: 0.001

SVM_optimize:
  C:
  - 1
  - 10
  - 100
  class_weight:
  - null
  - balanced
  coef0:
  - 0.0
  - 0.8
  - 100.0
  degree:
  - 1
  - 3
  - 5
  gamma:
  - auto
  kernel:
  - rbf
  random_state:
  - 46

# RF settings
RF_parameters:
  class_weight: balanced
  max_depth: null
  max_features: sqrt
  n_estimators: 200
  n_jobs: -1
  oob_score: true
  random_state: 46

RF_optimize:
  class_weight:
  - null
  - balanced
  max_features:
  - sqrt
  - log2
  n_estimators: !!python/object/apply:builtins.range
  - 50
  - 200
  - 50
  oob_score:
  - true
  random_state:
  - 46

# conformal predictor settings
conformal: false
conformalSignificance: 0.1
